# Generated by Django 5.2.11 on 2026-02-23 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("qrcodes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPageTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bio_link", "Bio / Link Tree"),
                            ("product", "Product Page"),
                            ("event", "Event Page"),
                            ("restaurant", "Restaurant Menu"),
                            ("portfolio", "Portfolio"),
                            ("contact", "Contact / vCard"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("thumbnail_url", models.URLField(blank=True, default="")),
                (
                    "html_template",
                    models.TextField(
                        help_text="Jinja2/Django template with {{ variables }}"
                    ),
                ),
                ("css", models.TextField(blank=True, default="")),
                (
                    "default_config",
                    models.JSONField(default=dict, help_text="Default variable values"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_premium", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "meta_description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("favicon_url", models.URLField(blank=True, default="")),
                ("html_content", models.TextField(help_text="Full HTML of the page")),
                ("custom_css", models.TextField(blank=True, default="")),
                (
                    "custom_js",
                    models.TextField(
                        blank=True, default="", help_text="Optional JS — sanitized"
                    ),
                ),
                ("page_config", models.JSONField(blank=True, default=dict)),
                ("show_qrgenie_badge", models.BooleanField(default=True)),
                (
                    "custom_domain",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_ai_generated", models.BooleanField(default=False)),
                ("ai_prompt", models.TextField(blank=True, default="")),
                ("is_published", models.BooleanField(default=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="landing_pages",
                        to="core.organization",
                    ),
                ),
                (
                    "qr_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="landing_pages",
                        to="qrcodes.qrcode",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="landing_pages.landingpagetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["slug"], name="landing_pag_slug_2cb12f_idx"),
                    models.Index(
                        fields=["organization", "-created_at"],
                        name="landing_pag_organiz_264119_idx",
                    ),
                ],
            },
        ),
    ]
