# Generated by Django 5.2.11 — Feature 14: Popup Builder

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("landing_pages", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Popup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Internal name for this popup", max_length=300)),
                ("popup_type", models.CharField(
                    choices=[("offer", "Offer / Promo"), ("form", "Lead Capture Form"), ("video", "Video Popup"), ("timer", "Countdown Timer")],
                    default="offer", max_length=20,
                )),
                ("trigger", models.CharField(
                    choices=[("on_load", "On Page Load"), ("delay", "After Delay"), ("scroll", "On Scroll %"), ("exit", "Exit Intent"), ("click", "Button Click")],
                    default="delay", max_length=20,
                )),
                ("trigger_value", models.IntegerField(default=3, help_text="Seconds for delay, % for scroll, ignored for others")),
                ("position", models.CharField(
                    choices=[("center", "Center Modal"), ("bottom", "Bottom Bar"), ("top", "Top Bar"), ("slide_left", "Slide-In Left"), ("slide_right", "Slide-In Right"), ("fullscreen", "Fullscreen")],
                    default="center", max_length=20,
                )),
                ("show_overlay", models.BooleanField(default=True, help_text="Dark background overlay")),
                ("allow_close", models.BooleanField(default=True, help_text="Show close button")),
                ("show_once", models.BooleanField(default=True, help_text="Only show once per visitor (cookie-based)")),
                ("frequency_hours", models.IntegerField(default=24, help_text="Hours before re-showing (if show_once=False)")),
                ("content", models.JSONField(blank=True, default=dict)),
                ("style", models.JSONField(blank=True, default=dict)),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("click_count", models.PositiveIntegerField(default=0)),
                ("submit_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("embed_token", models.UUIDField(db_index=True, default=uuid.uuid4, help_text="Token for embed script URL", unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="popups", to="core.organization")),
                ("landing_page", models.ForeignKey(
                    blank=True, help_text="Optionally link to a landing page",
                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                    related_name="popups", to="landing_pages.landingpage",
                )),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Popup",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="popup",
            index=models.Index(fields=["organization", "-created_at"], name="landing_pag_organiz_popup_idx"),
        ),
        migrations.AddIndex(
            model_name="popup",
            index=models.Index(fields=["embed_token"], name="landing_pag_embed_t_popup_idx"),
        ),
        migrations.CreateModel(
            name="PopupSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("data", models.JSONField(default=dict, help_text="Form field values")),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("page_url", models.URLField(blank=True, default="", help_text="Page where form was submitted")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("popup", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="landing_pages.popup")),
            ],
            options={
                "verbose_name": "Popup Submission",
                "ordering": ["-created_at"],
            },
        ),
    ]
