# Generated by Django 5.2.11 on 2026-03-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="allowed_domains",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Allowed destination domains (e.g. ["example.com","*.example.com"]). Empty = all allowed.',
            ),
        ),
    ]
