# Generated by Django 5.2.11 on 2026-02-23 16:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "secret",
                    models.CharField(help_text="HMAC signing secret", max_length=128),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list, help_text="List of event types to subscribe to"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("custom_headers", models.JSONField(blank=True, default=dict)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                (
                    "disabled_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhook_endpoints",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("retrying", "Retrying"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("request_headers", models.JSONField(default=dict)),
                (
                    "response_status_code",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("response_body", models.TextField(blank=True, default="")),
                ("response_headers", models.JSONField(blank=True, default=dict)),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("max_attempts", models.PositiveSmallIntegerField(default=5)),
                ("next_retry_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "ordering": ["-delivered_at"],
                "indexes": [
                    models.Index(
                        fields=["endpoint", "-delivered_at"],
                        name="webhooks_we_endpoin_8f4999_idx",
                    ),
                    models.Index(
                        fields=["status", "next_retry_at"],
                        name="webhooks_we_status_eb2625_idx",
                    ),
                ],
            },
        ),
    ]
