# Generated by Django 5.2.11 on 2026-02-23 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Automation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("scan_created", "QR Code Scanned"),
                            ("scan_from_country", "Scan From Country"),
                            ("scan_device_type", "Scan From Device Type"),
                            ("scan_limit_reached", "Scan Limit Reached"),
                            ("qr_expired", "QR Code Expired"),
                            ("qr_created", "QR Code Created"),
                            ("bulk_upload_completed", "Bulk Upload Completed"),
                            ("schedule", "Scheduled (Cron)"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("draft", "Draft"),
                            ("error", "Error"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='Cron expression for schedule trigger (e.g. "0 9 * * 1" for Mon 9AM)',
                        max_length=100,
                    ),
                ),
                ("total_runs", models.PositiveIntegerField(default=0)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("send_email", "Send Email"),
                            ("send_sms", "Send SMS"),
                            ("send_whatsapp", "Send WhatsApp Message"),
                            ("send_slack", "Send Slack Notification"),
                            ("send_teams", "Send MS Teams Notification"),
                            ("webhook", "Call Webhook URL"),
                            ("update_qr", "Update QR Code"),
                            ("pause_qr", "Pause QR Code"),
                            ("activate_qr", "Activate QR Code"),
                            ("ai_generate_page", "AI Generate Landing Page"),
                            ("ai_optimize_route", "AI Optimize Routing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text='Action config. Examples:\nsend_email: {"to": "a@b.com", "subject": "...", "template": "scan_alert"}\nwebhook: {"url": "https://...", "method": "POST", "headers": {...}}\nsend_slack: {"webhook_url": "https://hooks.slack.com/...", "message": "..."}\nupdate_qr: {"field": "destination_url", "value": "https://new-url.com"}\nai_generate_page: {"prompt": "Create a product page for..."}',
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AutomationActionLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_data", models.JSONField(default=dict)),
                ("output_data", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True, default="")),
                ("executed_at", models.DateTimeField(auto_now_add=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["executed_at"],
            },
        ),
        migrations.CreateModel(
            name="AutomationCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        help_text="e.g. country, device_type, os, browser, scan_count",
                        max_length=100,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("eq", "Equals"),
                            ("neq", "Not Equals"),
                            ("contains", "Contains"),
                            ("gt", "Greater Than"),
                            ("lt", "Less Than"),
                            ("gte", "Greater or Equal"),
                            ("lte", "Less or Equal"),
                            ("in", "In List"),
                            ("not_in", "Not In List"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.CharField(max_length=500)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="AutomationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped — Conditions Not Met"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "trigger_data",
                    models.JSONField(default=dict, help_text="Trigger event payload"),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
    ]
