# Generated by Django 5.2.11 on 2026-02-23 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("automation", "0001_initial"),
        ("core", "0001_initial"),
        ("qrcodes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="automation",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="automations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="automation",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automations",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="automation",
            name="qr_code",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, trigger only fires for this QR.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="automations",
                to="qrcodes.qrcode",
            ),
        ),
        migrations.AddField(
            model_name="automationaction",
            name="automation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="automation.automation",
            ),
        ),
        migrations.AddField(
            model_name="automationactionlog",
            name="action",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="automation.automationaction",
            ),
        ),
        migrations.AddField(
            model_name="automationcondition",
            name="automation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conditions",
                to="automation.automation",
            ),
        ),
        migrations.AddField(
            model_name="automationrun",
            name="automation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="automation.automation",
            ),
        ),
        migrations.AddField(
            model_name="automationactionlog",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="action_logs",
                to="automation.automationrun",
            ),
        ),
        migrations.AddIndex(
            model_name="automation",
            index=models.Index(
                fields=["organization", "status"], name="automation__organiz_14f44d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automation",
            index=models.Index(
                fields=["trigger_type"], name="automation__trigger_11c44b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="automationrun",
            index=models.Index(
                fields=["automation", "-started_at"],
                name="automation__automat_25b133_idx",
            ),
        ),
    ]
