# Generated by Django 5.2.11 on 2026-03-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("automation", "0003_add_schedules_and_hooks"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="externalhooksubscription",
            new_name="automation__organiz_1ba86f_idx",
            old_name="automation__org_evt_hook_idx",
        ),
        migrations.RenameIndex(
            model_name="qrschedule",
            new_name="automation__is_acti_eaf8cc_idx",
            old_name="automation__is_acti_sched_idx",
        ),
        migrations.RenameIndex(
            model_name="qrschedule",
            new_name="automation__qr_code_2e2447_idx",
            old_name="automation__qr_cod_sched_idx",
        ),
        migrations.AlterField(
            model_name="automationcondition",
            name="value",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
