# Generated by Django 5.2.11 on 2026-02-23 16:02

import apps.qrcodes.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkUploadJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=500)),
                ("file_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(default=0)),
                ("processed_rows", models.IntegerField(default=0)),
                ("success_count", models.IntegerField(default=0)),
                ("error_count", models.IntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                ("result_zip_url", models.URLField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.CharField(
                        db_index=True,
                        default=apps.qrcodes.models.generate_slug,
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "qr_type",
                    models.CharField(
                        choices=[
                            ("url", "Direct URL"),
                            ("multi_link", "Multi-Link Page"),
                            ("landing_page", "AI Landing Page"),
                            ("file", "File Download"),
                            ("payment", "Payment QR"),
                            ("chat", "Chat QR"),
                            ("wifi", "WiFi QR"),
                            ("vcard", "vCard Contact"),
                        ],
                        default="url",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("expired", "Expired"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "destination_url",
                    models.URLField(
                        blank=True,
                        help_text="Primary destination URL",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "fallback_url",
                    models.URLField(
                        blank=True,
                        help_text="Fallback URL when no rules match",
                        max_length=2048,
                        null=True,
                    ),
                ),
                (
                    "qr_image_url",
                    models.URLField(
                        blank=True, help_text="Stored QR image URL", null=True
                    ),
                ),
                ("foreground_color", models.CharField(default="#000000", max_length=7)),
                ("background_color", models.CharField(default="#FFFFFF", max_length=7)),
                (
                    "logo_url",
                    models.URLField(
                        blank=True, help_text="Center logo overlay", null=True
                    ),
                ),
                (
                    "error_correction",
                    models.CharField(
                        choices=[
                            ("L", "Low (7%)"),
                            ("M", "Medium (15%)"),
                            ("Q", "Quartile (25%)"),
                            ("H", "High (30%)"),
                        ],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(
                        blank=True, help_text="bcrypt hash", max_length=128, null=True
                    ),
                ),
                ("is_password_protected", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "scan_limit",
                    models.IntegerField(
                        blank=True, help_text="Max total scans allowed", null=True
                    ),
                ),
                ("total_scans", models.IntegerField(default=0)),
                ("unique_scans", models.IntegerField(default=0)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("folder", models.CharField(blank=True, default="", max_length=255)),
                ("current_version", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qr_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("upi", "UPI"),
                            ("stripe", "Stripe"),
                            ("razorpay", "Razorpay"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="INR", max_length=3)),
                ("upi_id", models.CharField(blank=True, max_length=255)),
                ("payment_link", models.URLField(blank=True, null=True)),
                ("merchant_name", models.CharField(blank=True, max_length=255)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qr_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_config",
                        to="qrcodes.qrcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MultiLinkItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField(max_length=2048)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name e.g. globe, instagram, youtube",
                        max_length=50,
                    ),
                ),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("click_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qr_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multi_links",
                        to="qrcodes.qrcode",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="FileAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(max_length=500)),
                ("file_url", models.URLField(max_length=2048)),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="Size in bytes"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("version", models.IntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                ("download_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qr_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="qrcodes.qrcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="ChatConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("whatsapp_number", models.CharField(blank=True, max_length=20)),
                (
                    "whatsapp_message",
                    models.TextField(blank=True, help_text="Pre-filled message"),
                ),
                ("telegram_username", models.CharField(blank=True, max_length=100)),
                ("messenger_page_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qr_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_config",
                        to="qrcodes.qrcode",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QRVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField()),
                (
                    "snapshot",
                    models.JSONField(help_text="Full QR state at this version"),
                ),
                ("change_summary", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "qr_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="qrcodes.qrcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("device", "Device Type"),
                            ("geo", "Geographic Location"),
                            ("time", "Time Schedule"),
                            ("language", "Browser Language"),
                            ("gps_radius", "GPS Radius (Geofence)"),
                            ("ab_test", "A/B Test"),
                            ("url_param", "URL Parameter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority rules evaluated first"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "conditions",
                    models.JSONField(
                        default=dict,
                        help_text='\n        Examples:\n        device: {"device_type": "mobile", "os": "android"}\n        geo: {"country": "IN", "city": "Bengaluru"}\n        time: {"start": "09:00", "end": "18:00", "timezone": "Asia/Kolkata", "days": ["mon","tue"]}\n        language: {"languages": ["en", "hi"]}\n        gps_radius: {"lat": 12.97, "lon": 77.59, "radius_meters": 500}\n        ab_test: {"variant": "A", "weight": 50}\n        url_param: {"key": "src", "value": "instagram"}\n    ',
                    ),
                ),
                ("destination_url", models.URLField(max_length=2048)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable rule label",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qr_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="qrcodes.qrcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-priority", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="qrcodes_qrc_organiz_3febbf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(fields=["slug"], name="qrcodes_qrc_slug_a0266b_idx"),
        ),
        migrations.AddIndex(
            model_name="qrcode",
            index=models.Index(fields=["status"], name="qrcodes_qrc_status_046e5d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="qrversion",
            unique_together={("qr_code", "version_number")},
        ),
    ]
