# Generated by Django 5.2.11 on 2026-02-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrcodes", "0005_languageroute"),
    ]

    operations = [
        migrations.AddField(
            model_name="languageroute",
            name="geo_direct",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Direct geo→URL: [{country,state,district?,url,label?}]",
            ),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="frame_text",
            field=models.CharField(
                blank=True, help_text='CTA text e.g. "Scan Me"', max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="gradient_end_color",
            field=models.CharField(
                blank=True, help_text="Gradient end colour", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="gradient_start_color",
            field=models.CharField(
                blank=True, help_text="Gradient start colour", max_length=7
            ),
        ),
        migrations.AlterField(
            model_name="qrcode",
            name="static_content",
            field=models.TextField(
                blank=True,
                help_text="Raw content for static QR (URL, text, vCard, WiFi, etc.)",
            ),
        ),
    ]
