# Generated by Django 5.2.11 on 2026-03-03 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrcodes", "0007_devicelocationcache_languageroute_mandatory"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "tz",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone e.g. Asia/Kolkata",
                        max_length=50,
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        default=list, help_text="Ordered time-window rules"
                    ),
                ),
                (
                    "default_url",
                    models.URLField(
                        blank=True,
                        help_text="Fallback URL when no time rule matches",
                        max_length=2048,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qr_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_schedule",
                        to="qrcodes.qrcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Time Schedule",
            },
        ),
    ]
