# Generated by Django 5.2.11 on 2026-03-03 13:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrcodes", "0008_time_schedule"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        help_text="Original uploaded filename", max_length=500
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        help_text="Relative path under MEDIA_ROOT", max_length=1024
                    ),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="Size in bytes"),
                ),
                (
                    "mime_type",
                    models.CharField(default="application/pdf", max_length=100),
                ),
                (
                    "page_count",
                    models.IntegerField(
                        default=0, help_text="Number of PDF pages (0=unknown)"
                    ),
                ),
                (
                    "access_token",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        help_text="Signed token for public viewer URL",
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "allow_download",
                    models.BooleanField(
                        default=False, help_text="Show download button in viewer"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Display title in viewer (defaults to filename)",
                        max_length=500,
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qr_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_document",
                        to="qrcodes.qrcode",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "PDF Document",
            },
        ),
    ]
