# Generated by Django 5.2.11 on 2026-03-06 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrcodes", "0016_tokenredirect_first_used_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deeplink",
            name="android_deep_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Android App Link (https://...) or custom URI scheme (myapp://...)",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="deeplink",
            name="android_fallback_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Fallback URL if app is not installed (e.g. Play Store link)",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="deeplink",
            name="custom_uri",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Custom URI scheme e.g. myapp://path/to/content",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="deeplink",
            name="fallback_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Fallback for desktop or when no platform matches",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="deeplink",
            name="ios_deep_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="iOS Universal Link (https://...) or custom URI scheme (myapp://...)",
                max_length=2048,
            ),
        ),
        migrations.AlterField(
            model_name="deeplink",
            name="ios_fallback_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Fallback URL if app is not installed (e.g. App Store link)",
                max_length=2048,
            ),
        ),
        migrations.CreateModel(
            name="QRExpiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "expiry_type",
                    models.CharField(
                        choices=[
                            ("date", "Expire by Date"),
                            ("datetime", "Expire by Date & Time"),
                            ("scan_count", "Expire by Scan Count"),
                        ],
                        default="date",
                        max_length=20,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="QR expires at end of this date (23:59:59 server time)",
                        null=True,
                    ),
                ),
                (
                    "expiry_datetime",
                    models.DateTimeField(
                        blank=True,
                        help_text="QR expires at this exact date & time",
                        null=True,
                    ),
                ),
                (
                    "max_scans",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Maximum number of scans before QR expires",
                    ),
                ),
                (
                    "scan_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Current number of scans counted"
                    ),
                ),
                (
                    "expired_redirect_url",
                    models.URLField(
                        blank=True,
                        help_text="Redirect to this URL when expired (blank = show expiry page)",
                        max_length=2048,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "qr_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expiry",
                        to="qrcodes.qrcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Expiry",
                "verbose_name_plural": "QR Expiries",
            },
        ),
    ]
