# Generated by Django 5.2.11 on 2026-03-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qrcodes", "0025_qrcode_freeze"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="digitalvcard",
            options={},
        ),
        migrations.AlterField(
            model_name="bulkuploadjob",
            name="file_url",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="productauth",
            name="product_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
