# Generated by Django 5.2.11 on 2026-02-23 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("total_scans", models.IntegerField(default=0)),
                ("unique_scans", models.IntegerField(default=0)),
                ("country_breakdown", models.JSONField(default=dict)),
                ("device_breakdown", models.JSONField(default=dict)),
                ("browser_breakdown", models.JSONField(default=dict)),
                ("os_breakdown", models.JSONField(default=dict)),
                (
                    "hourly_breakdown",
                    models.JSONField(default=dict, help_text="Hour → count mapping"),
                ),
                ("referrer_breakdown", models.JSONField(default=dict)),
                ("link_clicks", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="LinkClickEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("link_url", models.URLField(max_length=2048)),
                ("link_label", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=5)),
                ("device_type", models.CharField(blank=True, max_length=20)),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-clicked_at"],
            },
        ),
        migrations.CreateModel(
            name="ScanEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, db_index=True, max_length=5)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "device_type",
                    models.CharField(blank=True, db_index=True, max_length=20),
                ),
                ("os", models.CharField(blank=True, max_length=30)),
                ("browser", models.CharField(blank=True, max_length=30)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True, max_length=2048)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("destination_url", models.URLField(blank=True, max_length=2048)),
                (
                    "rule_matched",
                    models.CharField(
                        blank=True,
                        help_text="ID of the rule that matched",
                        max_length=100,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("is_unique", models.BooleanField(default=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("scanned_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-scanned_at"],
            },
        ),
    ]
