# Generated by Django 5.2.11 on 2026-02-23 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("qrcodes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailymetric",
            name="qr_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_metrics",
                to="qrcodes.qrcode",
            ),
        ),
        migrations.AddField(
            model_name="linkclickevent",
            name="qr_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="link_clicks",
                to="qrcodes.qrcode",
            ),
        ),
        migrations.AddField(
            model_name="scanevent",
            name="qr_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scan_events",
                to="qrcodes.qrcode",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailymetric",
            unique_together={("qr_code", "date")},
        ),
        migrations.AddIndex(
            model_name="scanevent",
            index=models.Index(
                fields=["qr_code", "-scanned_at"], name="analytics_s_qr_code_641af2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanevent",
            index=models.Index(
                fields=["country", "-scanned_at"], name="analytics_s_country_9cd53c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scanevent",
            index=models.Index(
                fields=["device_type", "-scanned_at"],
                name="analytics_s_device__99a4d7_idx",
            ),
        ),
    ]
