# Generated by Django 5.2.11 on 2026-03-08 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0002_initial"),
        ("qrcodes", "0028_qrcode_animated_qr"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. form_submit, purchase, signup, page_view, download",
                        max_length=50,
                    ),
                ),
                (
                    "event_label",
                    models.CharField(
                        blank=True, help_text="Human-readable label", max_length=255
                    ),
                ),
                (
                    "event_value",
                    models.FloatField(
                        default=0, help_text="Monetary value or numeric score"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=5)),
                ("device_type", models.CharField(blank=True, max_length=20)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Links conversion to a scan session",
                        max_length=64,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "qr_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_events",
                        to="qrcodes.qrcode",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["qr_code", "-created_at"],
                        name="analytics_c_qr_code_c2f2f9_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="analytics_c_event_t_e46f11_idx",
                    ),
                ],
            },
        ),
    ]
