# Generated by Django 5.2.11 on 2026-02-23 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIGenerationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "generation_type",
                    models.CharField(
                        choices=[
                            ("landing_page", "Landing Page Generation"),
                            ("analytics_summary", "Analytics Summary"),
                            ("route_suggestion", "Smart Route Suggestion"),
                            ("anomaly_detection", "Anomaly Detection"),
                            ("ab_optimizer", "A/B Test Optimizer"),
                            ("qr_description", "QR Description Generator"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField()),
                ("model_used", models.CharField(default="gpt-4o", max_length=100)),
                ("temperature", models.FloatField(default=0.7)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("raw_response", models.TextField(blank=True, default="")),
                ("prompt_tokens", models.PositiveIntegerField(default=0)),
                ("completion_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
