# Generated by Django 5.2.11 on 2026-02-23 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ai_service", "0001_initial"),
        ("core", "0001_initial"),
        ("qrcodes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aigenerationlog",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ai_logs",
                to="core.organization",
            ),
        ),
        migrations.AddField(
            model_name="aigenerationlog",
            name="qr_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="qrcodes.qrcode",
            ),
        ),
        migrations.AddField(
            model_name="aigenerationlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="aigenerationlog",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="ai_service__organiz_ea2404_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aigenerationlog",
            index=models.Index(
                fields=["generation_type"], name="ai_service__generat_8fa2b9_idx"
            ),
        ),
    ]
